services:
  - type: web
    name: lakshmi-ai-wife
    env: python
    region: oregon  # Optional: pick closest region
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DHAN_CLIENT_ID
        sync: false
      - key: DHAN_ACCESS_TOKEN
        sync: false
      - key: OTHER_SECRET
        sync: false
